INSERT INTO countries (name_fr, name_en, iso2, iso3, flag_url) VALUES
('Andorre','Andorra','AD','AND','https://flagcdn.com/w320/ad.png'),
('Émirats arabes unis','United Arab Emirates','AE','ARE','https://flagcdn.com/w320/ae.png'),
('Afghanistan','Afghanistan','AF','AFG','https://flagcdn.com/w320/af.png'),
('Antigua-et-Barbuda','Antigua and Barbuda','AG','ATG','https://flagcdn.com/w320/ag.png'),
('Anguilla','Anguilla','AI','AIA','https://flagcdn.com/w320/ai.png'),
('Albanie','Albania','AL','ALB','https://flagcdn.com/w320/al.png'),
('Arménie','Armenia','AM','ARM','https://flagcdn.com/w320/am.png'),
('Angola','Angola','AO','AGO','https://flagcdn.com/w320/ao.png'),
('Antarctique','Antarctica','AQ','ATA','https://flagcdn.com/w320/aq.png'),
('Argentine','Argentina','AR','ARG','https://flagcdn.com/w320/ar.png'),
('Samoa américaines','American Samoa','AS','ASM','https://flagcdn.com/w320/as.png'),
('Autriche','Austria','AT','AUT','https://flagcdn.com/w320/at.png'),
('Australie','Australia','AU','AUS','https://flagcdn.com/w320/au.png'),
('Aruba','Aruba','AW','ABW','https://flagcdn.com/w320/aw.png'),
('Ahvenanmaa','Åland Islands','AX','ALA','https://flagcdn.com/w320/ax.png'),
('Azerbaïdjan','Azerbaijan','AZ','AZE','https://flagcdn.com/w320/az.png'),
('Bosnie-Herzégovine','Bosnia and Herzegovina','BA','BIH','https://flagcdn.com/w320/ba.png'),
('Barbade','Barbados','BB','BRB','https://flagcdn.com/w320/bb.png'),
('Bangladesh','Bangladesh','BD','BGD','https://flagcdn.com/w320/bd.png'),
('Belgique','Belgium','BE','BEL','https://flagcdn.com/w320/be.png'),
('Burkina Faso','Burkina Faso','BF','BFA','https://flagcdn.com/w320/bf.png'),
('Bulgarie','Bulgaria','BG','BGR','https://flagcdn.com/w320/bg.png'),
('Bahreïn','Bahrain','BH','BHR','https://flagcdn.com/w320/bh.png'),
('Burundi','Burundi','BI','BDI','https://flagcdn.com/w320/bi.png'),
('Bénin','Benin','BJ','BEN','https://flagcdn.com/w320/bj.png'),
('Saint-Barthélemy','Saint Barthélemy','BL','BLM','https://flagcdn.com/w320/bl.png'),
('Bermudes','Bermuda','BM','BMU','https://flagcdn.com/w320/bm.png'),
('Brunei','Brunei','BN','BRN','https://flagcdn.com/w320/bn.png'),
('Bolivie','Bolivia','BO','BOL','https://flagcdn.com/w320/bo.png'),
('Pays-Bas caribéens','Caribbean Netherlands','BQ','BES','https://flagcdn.com/w320/bq.png'),
('Brésil','Brazil','BR','BRA','https://flagcdn.com/w320/br.png'),
('Bahamas','Bahamas','BS','BHS','https://flagcdn.com/w320/bs.png'),
('Bhoutan','Bhutan','BT','BTN','https://flagcdn.com/w320/bt.png'),
('Île Bouvet','Bouvet Island','BV','BVT','https://flagcdn.com/w320/bv.png'),
('Botswana','Botswana','BW','BWA','https://flagcdn.com/w320/bw.png'),
('Biélorussie','Belarus','BY','BLR','https://flagcdn.com/w320/by.png'),
('Belize','Belize','BZ','BLZ','https://flagcdn.com/w320/bz.png'),
('Canada','Canada','CA','CAN','https://flagcdn.com/w320/ca.png'),
('Îles Cocos','Cocos (Keeling) Islands','CC','CCK','https://flagcdn.com/w320/cc.png'),
('Congo (Rép. dém.)','DR Congo','CD','COD','https://flagcdn.com/w320/cd.png'),
('République centrafricaine','Central African Republic','CF','CAF','https://flagcdn.com/w320/cf.png'),
('Congo','Republic of the Congo','CG','COG','https://flagcdn.com/w320/cg.png'),
('Suisse','Switzerland','CH','CHE','https://flagcdn.com/w320/ch.png'),
('Côte d''Ivoire','Ivory Coast','CI','CIV','https://flagcdn.com/w320/ci.png'),
('Îles Cook','Cook Islands','CK','COK','https://flagcdn.com/w320/ck.png'),
('Chili','Chile','CL','CHL','https://flagcdn.com/w320/cl.png'),
('Cameroun','Cameroon','CM','CMR','https://flagcdn.com/w320/cm.png'),
('Chine','China','CN','CHN','https://flagcdn.com/w320/cn.png'),
('Colombie','Colombia','CO','COL','https://flagcdn.com/w320/co.png'),
('Costa Rica','Costa Rica','CR','CRI','https://flagcdn.com/w320/cr.png'),
('Cuba','Cuba','CU','CUB','https://flagcdn.com/w320/cu.png'),
('Îles du Cap-Vert','Cape Verde','CV','CPV','https://flagcdn.com/w320/cv.png'),
('Curaçao','Curaçao','CW','CUW','https://flagcdn.com/w320/cw.png'),
('Île Christmas','Christmas Island','CX','CXR','https://flagcdn.com/w320/cx.png'),
('Chypre','Cyprus','CY','CYP','https://flagcdn.com/w320/cy.png'),
('Tchéquie','Czechia','CZ','CZE','https://flagcdn.com/w320/cz.png'),
('Allemagne','Germany','DE','DEU','https://flagcdn.com/w320/de.png'),
('Djibouti','Djibouti','DJ','DJI','https://flagcdn.com/w320/dj.png'),
('Danemark','Denmark','DK','DNK','https://flagcdn.com/w320/dk.png'),
('Dominique','Dominica','DM','DMA','https://flagcdn.com/w320/dm.png'),
('République dominicaine','Dominican Republic','DO','DOM','https://flagcdn.com/w320/do.png'),
('Algérie','Algeria','DZ','DZA','https://flagcdn.com/w320/dz.png'),
('Équateur','Ecuador','EC','ECU','https://flagcdn.com/w320/ec.png'),
('Estonie','Estonia','EE','EST','https://flagcdn.com/w320/ee.png'),
('Égypte','Egypt','EG','EGY','https://flagcdn.com/w320/eg.png'),
('Sahara Occidental','Western Sahara','EH','ESH','https://flagcdn.com/w320/eh.png'),
('Érythrée','Eritrea','ER','ERI','https://flagcdn.com/w320/er.png'),
('Espagne','Spain','ES','ESP','https://flagcdn.com/w320/es.png'),
('Éthiopie','Ethiopia','ET','ETH','https://flagcdn.com/w320/et.png'),
('Finlande','Finland','FI','FIN','https://flagcdn.com/w320/fi.png'),
('Fidji','Fiji','FJ','FJI','https://flagcdn.com/w320/fj.png'),
('Îles Malouines','Falkland Islands','FK','FLK','https://flagcdn.com/w320/fk.png'),
('Micronésie','Micronesia','FM','FSM','https://flagcdn.com/w320/fm.png'),
('Îles Féroé','Faroe Islands','FO','FRO','https://flagcdn.com/w320/fo.png'),
('France','France','FR','FRA','https://flagcdn.com/w320/fr.png'),
('Gabon','Gabon','GA','GAB','https://flagcdn.com/w320/ga.png'),
('Royaume-Uni','United Kingdom','GB','GBR','https://flagcdn.com/w320/gb.png'),
('Grenade','Grenada','GD','GRD','https://flagcdn.com/w320/gd.png'),
('Géorgie','Georgia','GE','GEO','https://flagcdn.com/w320/ge.png'),
('Guyane','French Guiana','GF','GUF','https://flagcdn.com/w320/gf.png'),
('Guernesey','Guernsey','GG','GGY','https://flagcdn.com/w320/gg.png'),
('Ghana','Ghana','GH','GHA','https://flagcdn.com/w320/gh.png'),
('Gibraltar','Gibraltar','GI','GIB','https://flagcdn.com/w320/gi.png'),
('Groenland','Greenland','GL','GRL','https://flagcdn.com/w320/gl.png'),
('Gambie','Gambia','GM','GMB','https://flagcdn.com/w320/gm.png'),
('Guinée','Guinea','GN','GIN','https://flagcdn.com/w320/gn.png'),
('Guadeloupe','Guadeloupe','GP','GLP','https://flagcdn.com/w320/gp.png'),
('Guinée équatoriale','Equatorial Guinea','GQ','GNQ','https://flagcdn.com/w320/gq.png'),
('Grèce','Greece','GR','GRC','https://flagcdn.com/w320/gr.png'),
('Géorgie du Sud-et-les Îles Sandwich du Sud','South Georgia','GS','SGS','https://flagcdn.com/w320/gs.png'),        
('Guatemala','Guatemala','GT','GTM','https://flagcdn.com/w320/gt.png'),
('Guam','Guam','GU','GUM','https://flagcdn.com/w320/gu.png'),
('Guinée-Bissau','Guinea-Bissau','GW','GNB','https://flagcdn.com/w320/gw.png'),
('Guyana','Guyana','GY','GUY','https://flagcdn.com/w320/gy.png'),
('Hong Kong','Hong Kong','HK','HKG','https://flagcdn.com/w320/hk.png'),
('Îles Heard-et-MacDonald','Heard Island and McDonald Islands','HM','HMD','https://flagcdn.com/w320/hm.png'),       
('Honduras','Honduras','HN','HND','https://flagcdn.com/w320/hn.png'),
('Croatie','Croatia','HR','HRV','https://flagcdn.com/w320/hr.png'),
('Haïti','Haiti','HT','HTI','https://flagcdn.com/w320/ht.png'),
('Hongrie','Hungary','HU','HUN','https://flagcdn.com/w320/hu.png'),
('Indonésie','Indonesia','ID','IDN','https://flagcdn.com/w320/id.png'),
('Irlande','Ireland','IE','IRL','https://flagcdn.com/w320/ie.png'),
('Israël','Israel','IL','ISR','https://flagcdn.com/w320/il.png'),
('Île de Man','Isle of Man','IM','IMN','https://flagcdn.com/w320/im.png'),
('Inde','India','IN','IND','https://flagcdn.com/w320/in.png'),
('Territoire britannique de l''océan Indien','British Indian Ocean Territory','IO','IOT','https://flagcdn.com/w320/io.png'),
('Irak','Iraq','IQ','IRQ','https://flagcdn.com/w320/iq.png'),
('Iran','Iran','IR','IRN','https://flagcdn.com/w320/ir.png'),
('Islande','Iceland','IS','ISL','https://flagcdn.com/w320/is.png'),
('Italie','Italy','IT','ITA','https://flagcdn.com/w320/it.png'),
('Jersey','Jersey','JE','JEY','https://flagcdn.com/w320/je.png'),
('Jamaïque','Jamaica','JM','JAM','https://flagcdn.com/w320/jm.png'),
('Jordanie','Jordan','JO','JOR','https://flagcdn.com/w320/jo.png'),
('Japon','Japan','JP','JPN','https://flagcdn.com/w320/jp.png'),
('Kenya','Kenya','KE','KEN','https://flagcdn.com/w320/ke.png'),
('Kirghizistan','Kyrgyzstan','KG','KGZ','https://flagcdn.com/w320/kg.png'),
('Cambodge','Cambodia','KH','KHM','https://flagcdn.com/w320/kh.png'),
('Kiribati','Kiribati','KI','KIR','https://flagcdn.com/w320/ki.png'),
('Comores','Comoros','KM','COM','https://flagcdn.com/w320/km.png'),
('Saint-Christophe-et-Niévès','Saint Kitts and Nevis','KN','KNA','https://flagcdn.com/w320/kn.png'),
('Corée du Nord','North Korea','KP','PRK','https://flagcdn.com/w320/kp.png'),
('Corée du Sud','South Korea','KR','KOR','https://flagcdn.com/w320/kr.png'),
('Koweït','Kuwait','KW','KWT','https://flagcdn.com/w320/kw.png'),
('Îles Caïmans','Cayman Islands','KY','CYM','https://flagcdn.com/w320/ky.png'),
('Kazakhstan','Kazakhstan','KZ','KAZ','https://flagcdn.com/w320/kz.png'),
('Laos','Laos','LA','LAO','https://flagcdn.com/w320/la.png'),
('Liban','Lebanon','LB','LBN','https://flagcdn.com/w320/lb.png'),
('Sainte-Lucie','Saint Lucia','LC','LCA','https://flagcdn.com/w320/lc.png'),
('Liechtenstein','Liechtenstein','LI','LIE','https://flagcdn.com/w320/li.png'),
('Sri Lanka','Sri Lanka','LK','LKA','https://flagcdn.com/w320/lk.png'),
('Liberia','Liberia','LR','LBR','https://flagcdn.com/w320/lr.png'),
('Lesotho','Lesotho','LS','LSO','https://flagcdn.com/w320/ls.png'),
('Lituanie','Lithuania','LT','LTU','https://flagcdn.com/w320/lt.png'),
('Luxembourg','Luxembourg','LU','LUX','https://flagcdn.com/w320/lu.png'),
('Lettonie','Latvia','LV','LVA','https://flagcdn.com/w320/lv.png'),
('Libye','Libya','LY','LBY','https://flagcdn.com/w320/ly.png'),
('Maroc','Morocco','MA','MAR','https://flagcdn.com/w320/ma.png'),
('Monaco','Monaco','MC','MCO','https://flagcdn.com/w320/mc.png'),
('Moldavie','Moldova','MD','MDA','https://flagcdn.com/w320/md.png'),
('Monténégro','Montenegro','ME','MNE','https://flagcdn.com/w320/me.png'),
('Saint-Martin','Saint Martin','MF','MAF','https://flagcdn.com/w320/mf.png'),
('Madagascar','Madagascar','MG','MDG','https://flagcdn.com/w320/mg.png'),
('Îles Marshall','Marshall Islands','MH','MHL','https://flagcdn.com/w320/mh.png'),
('Macédoine du Nord','North Macedonia','MK','MKD','https://flagcdn.com/w320/mk.png'),
('Mali','Mali','ML','MLI','https://flagcdn.com/w320/ml.png'),
('Birmanie','Myanmar','MM','MMR','https://flagcdn.com/w320/mm.png'),
('Mongolie','Mongolia','MN','MNG','https://flagcdn.com/w320/mn.png'),
('Macao','Macau','MO','MAC','https://flagcdn.com/w320/mo.png'),
('Îles Mariannes du Nord','Northern Mariana Islands','MP','MNP','https://flagcdn.com/w320/mp.png'),
('Martinique','Martinique','MQ','MTQ','https://flagcdn.com/w320/mq.png'),
('Mauritanie','Mauritania','MR','MRT','https://flagcdn.com/w320/mr.png'),
('Montserrat','Montserrat','MS','MSR','https://flagcdn.com/w320/ms.png'),
('Malte','Malta','MT','MLT','https://flagcdn.com/w320/mt.png'),
('Île Maurice','Mauritius','MU','MUS','https://flagcdn.com/w320/mu.png'),
('Maldives','Maldives','MV','MDV','https://flagcdn.com/w320/mv.png'),
('Malawi','Malawi','MW','MWI','https://flagcdn.com/w320/mw.png'),
('Mexique','Mexico','MX','MEX','https://flagcdn.com/w320/mx.png'),
('Malaisie','Malaysia','MY','MYS','https://flagcdn.com/w320/my.png'),
('Mozambique','Mozambique','MZ','MOZ','https://flagcdn.com/w320/mz.png'),
('Namibie','Namibia','NA','NAM','https://flagcdn.com/w320/na.png'),
('Nouvelle-Calédonie','New Caledonia','NC','NCL','https://flagcdn.com/w320/nc.png'),
('Niger','Niger','NE','NER','https://flagcdn.com/w320/ne.png'),
('Île Norfolk','Norfolk Island','NF','NFK','https://flagcdn.com/w320/nf.png'),
('Nigéria','Nigeria','NG','NGA','https://flagcdn.com/w320/ng.png'),
('Nicaragua','Nicaragua','NI','NIC','https://flagcdn.com/w320/ni.png'),
('Pays-Bas','Netherlands','NL','NLD','https://flagcdn.com/w320/nl.png'),
('Norvège','Norway','NO','NOR','https://flagcdn.com/w320/no.png'),
('Népal','Nepal','NP','NPL','https://flagcdn.com/w320/np.png'),
('Nauru','Nauru','NR','NRU','https://flagcdn.com/w320/nr.png'),
('Niue','Niue','NU','NIU','https://flagcdn.com/w320/nu.png'),
('Nouvelle-Zélande','New Zealand','NZ','NZL','https://flagcdn.com/w320/nz.png'),
('Oman','Oman','OM','OMN','https://flagcdn.com/w320/om.png'),
('Panama','Panama','PA','PAN','https://flagcdn.com/w320/pa.png'),
('Pérou','Peru','PE','PER','https://flagcdn.com/w320/pe.png'),
('Polynésie française','French Polynesia','PF','PYF','https://flagcdn.com/w320/pf.png'),
('Papouasie-Nouvelle-Guinée','Papua New Guinea','PG','PNG','https://flagcdn.com/w320/pg.png'),
('Philippines','Philippines','PH','PHL','https://flagcdn.com/w320/ph.png'),
('Pakistan','Pakistan','PK','PAK','https://flagcdn.com/w320/pk.png'),
('Pologne','Poland','PL','POL','https://flagcdn.com/w320/pl.png'),
('Saint-Pierre-et-Miquelon','Saint Pierre and Miquelon','PM','SPM','https://flagcdn.com/w320/pm.png'),
('Îles Pitcairn','Pitcairn Islands','PN','PCN','https://flagcdn.com/w320/pn.png'),
('Porto Rico','Puerto Rico','PR','PRI','https://flagcdn.com/w320/pr.png'),
('Palestine','Palestine','PS','PSE','https://flagcdn.com/w320/ps.png'),
('Portugal','Portugal','PT','PRT','https://flagcdn.com/w320/pt.png'),
('Palaos (Palau)','Palau','PW','PLW','https://flagcdn.com/w320/pw.png'),
('Paraguay','Paraguay','PY','PRY','https://flagcdn.com/w320/py.png'),
('Qatar','Qatar','QA','QAT','https://flagcdn.com/w320/qa.png'),
('Réunion','Réunion','RE','REU','https://flagcdn.com/w320/re.png'),
('Roumanie','Romania','RO','ROU','https://flagcdn.com/w320/ro.png'),
('Serbie','Serbia','RS','SRB','https://flagcdn.com/w320/rs.png'),
('Russie','Russia','RU','RUS','https://flagcdn.com/w320/ru.png'),
('Rwanda','Rwanda','RW','RWA','https://flagcdn.com/w320/rw.png'),
('Arabie Saoudite','Saudi Arabia','SA','SAU','https://flagcdn.com/w320/sa.png'),
('Îles Salomon','Solomon Islands','SB','SLB','https://flagcdn.com/w320/sb.png'),
('Seychelles','Seychelles','SC','SYC','https://flagcdn.com/w320/sc.png'),
('Soudan','Sudan','SD','SDN','https://flagcdn.com/w320/sd.png'),
('Suède','Sweden','SE','SWE','https://flagcdn.com/w320/se.png'),
('Singapour','Singapore','SG','SGP','https://flagcdn.com/w320/sg.png'),
('Sainte-Hélène, Ascension et Tristan da Cunha','Saint Helena, Ascension and Tristan da Cunha','SH','SHN','https://flagcdn.com/w320/sh.png'),
('Slovénie','Slovenia','SI','SVN','https://flagcdn.com/w320/si.png'),
('Svalbard et Jan Mayen','Svalbard and Jan Mayen','SJ','SJM','https://flagcdn.com/w320/sj.png'),
('Slovaquie','Slovakia','SK','SVK','https://flagcdn.com/w320/sk.png'),
('Sierra Leone','Sierra Leone','SL','SLE','https://flagcdn.com/w320/sl.png'),
('Saint-Marin','San Marino','SM','SMR','https://flagcdn.com/w320/sm.png'),
('Sénégal','Senegal','SN','SEN','https://flagcdn.com/w320/sn.png'),
('Somalie','Somalia','SO','SOM','https://flagcdn.com/w320/so.png'),
('Surinam','Suriname','SR','SUR','https://flagcdn.com/w320/sr.png'),
('Soudan du Sud','South Sudan','SS','SSD','https://flagcdn.com/w320/ss.png'),
('São Tomé et Príncipe','São Tomé and Príncipe','ST','STP','https://flagcdn.com/w320/st.png'),
('Salvador','El Salvador','SV','SLV','https://flagcdn.com/w320/sv.png'),
('Saint-Martin','Sint Maarten','SX','SXM','https://flagcdn.com/w320/sx.png'),
('Syrie','Syria','SY','SYR','https://flagcdn.com/w320/sy.png'),
('Swaziland','Eswatini','SZ','SWZ','https://flagcdn.com/w320/sz.png'),
('Îles Turques-et-Caïques','Turks and Caicos Islands','TC','TCA','https://flagcdn.com/w320/tc.png'),
('Tchad','Chad','TD','TCD','https://flagcdn.com/w320/td.png'),
('Terres australes et antarctiques françaises','French Southern and Antarctic Lands','TF','ATF','https://flagcdn.com/w320/tf.png'),
('Togo','Togo','TG','TGO','https://flagcdn.com/w320/tg.png'),
('Thaïlande','Thailand','TH','THA','https://flagcdn.com/w320/th.png'),
('Tadjikistan','Tajikistan','TJ','TJK','https://flagcdn.com/w320/tj.png'),
('Tokelau','Tokelau','TK','TKL','https://flagcdn.com/w320/tk.png'),
('Timor oriental','Timor-Leste','TL','TLS','https://flagcdn.com/w320/tl.png'),
('Turkménistan','Turkmenistan','TM','TKM','https://flagcdn.com/w320/tm.png'),
('Tunisie','Tunisia','TN','TUN','https://flagcdn.com/w320/tn.png'),
('Tonga','Tonga','TO','TON','https://flagcdn.com/w320/to.png'),
('Turquie','Turkey','TR','TUR','https://flagcdn.com/w320/tr.png'),
('Trinité-et-Tobago','Trinidad and Tobago','TT','TTO','https://flagcdn.com/w320/tt.png'),
('Tuvalu','Tuvalu','TV','TUV','https://flagcdn.com/w320/tv.png'),
('Taïwan','Taiwan','TW','TWN','https://flagcdn.com/w320/tw.png'),
('Tanzanie','Tanzania','TZ','TZA','https://flagcdn.com/w320/tz.png'),
('Ukraine','Ukraine','UA','UKR','https://flagcdn.com/w320/ua.png'),
('Ouganda','Uganda','UG','UGA','https://flagcdn.com/w320/ug.png'),
('Îles mineures éloignées des États-Unis','United States Minor Outlying Islands','UM','UMI','https://flagcdn.com/w320/um.png'),
('États-Unis','United States','US','USA','https://flagcdn.com/w320/us.png'),
('Uruguay','Uruguay','UY','URY','https://flagcdn.com/w320/uy.png'),
('Ouzbékistan','Uzbekistan','UZ','UZB','https://flagcdn.com/w320/uz.png'),
('Cité du Vatican','Vatican City','VA','VAT','https://flagcdn.com/w320/va.png'),
('Saint-Vincent-et-les-Grenadines','Saint Vincent and the Grenadines','VC','VCT','https://flagcdn.com/w320/vc.png'),
('Venezuela','Venezuela','VE','VEN','https://flagcdn.com/w320/ve.png'),
('Îles Vierges britanniques','British Virgin Islands','VG','VGB','https://flagcdn.com/w320/vg.png'),
('Îles Vierges des États-Unis','United States Virgin Islands','VI','VIR','https://flagcdn.com/w320/vi.png'),        
('Viêt Nam','Vietnam','VN','VNM','https://flagcdn.com/w320/vn.png'),
('Vanuatu','Vanuatu','VU','VUT','https://flagcdn.com/w320/vu.png'),
('Wallis-et-Futuna','Wallis and Futuna','WF','WLF','https://flagcdn.com/w320/wf.png'),
('Samoa','Samoa','WS','WSM','https://flagcdn.com/w320/ws.png'),
('Kosovo','Kosovo','XK','UNK','https://flagcdn.com/w320/xk.png'),
('Yémen','Yemen','YE','YEM','https://flagcdn.com/w320/ye.png'),
('Mayotte','Mayotte','YT','MYT','https://flagcdn.com/w320/yt.png'),
('Afrique du Sud','South Africa','ZA','ZAF','https://flagcdn.com/w320/za.png'),
('Zambie','Zambia','ZM','ZMB','https://flagcdn.com/w320/zm.png'),
('Zimbabwe','Zimbabwe','ZW','ZWE','https://flagcdn.com/w320/zw.png')
ON CONFLICT (iso2) DO NOTHING;
